export const trending = {
  page: 1,
  results: [
    {
      original_language: "en",
      original_title: "The King's Man",
      poster_path: "/aq4Pwv5Xeuvj6HZKtxyd23e6bE9.jpg",
      id: 476669,
      video: false,
      vote_average: 7.1,
      title: "The King's Man",
      overview:
        "As a collection of history's worst tyrants and criminal masterminds gather to plot a war to wipe out millions, one man must race against time to stop them.",
      release_date: "2021-12-22",
      adult: false,
      backdrop_path: "/4OTYefcAlaShn6TGVK33UxLW9R7.jpg",
      genre_ids: [28, 12, 53, 10752],
      vote_count: 1323,
      popularity: 3739.757,
      media_type: "movie",
    },
    {
      adult: false,
      backdrop_path: "/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
      genre_ids: [28, 12, 878],
      original_language: "en",
      original_title: "Spider-Man: No Way Home",
      poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
      video: false,
      vote_average: 8.3,
      vote_count: 8256,
      overview:
        "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
      release_date: "2021-12-15",
      title: "Spider-Man: No Way Home",
      id: 634649,
      popularity: 6855.906,
      media_type: "movie",
    },
    {
      original_language: "en",
      original_title: "Texas Chainsaw Massacre",
      poster_path: "/meRIRfADEGVo65xgPO6eZvJ0CRG.jpg",
      title: "Texas Chainsaw Massacre",
      overview:
        "In this sequel, influencers looking to breathe new life into a Texas ghost town encounter Leatherface, an infamous killer who wears a mask of human skin.",
      id: 632727,
      vote_average: 5.2,
      vote_count: 341,
      adult: false,
      backdrop_path: "/aTSA5zMWlVFTYBIZxTCMbLkfOtb.jpg",
      video: false,
      genre_ids: [27],
      release_date: "2022-02-18",
      popularity: 619.57,
      media_type: "movie",
    },
    {
      vote_average: 6.9,
      overview:
        "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.",
      id: 646385,
      title: "Scream",
      adult: false,
      backdrop_path: "/usaZV7KB6Man9Rm9TyDAeQf7uVD.jpg",
      genre_ids: [27, 9648, 53],
      vote_count: 618,
      original_language: "en",
      original_title: "Scream",
      poster_path: "/kZNHR1upJKF3eTzdgl5V8s8a4C3.jpg",
      release_date: "2022-01-12",
      video: false,
      popularity: 3464.303,
      media_type: "movie",
    },
    {
      original_language: "en",
      poster_path: "/jtnfNzqZwN4E32FGGxx1YZaBWWf.jpg",
      vote_average: 8.4,
      original_name: "Euphoria",
      origin_country: ["US"],
      vote_count: 6930,
      overview:
        "A group of high school students navigate love and friendships in a world of drugs, sex, trauma, and social media.",
      first_air_date: "2019-06-16",
      name: "Euphoria",
      backdrop_path: "/9KnIzPCv9XpWA0MqmwiKBZvV1Sj.jpg",
      id: 85552,
      genre_ids: [18],
      popularity: 5452.129,
      media_type: "tv",
    },
    {
      genre_ids: [28, 12],
      original_language: "en",
      original_title: "Uncharted",
      poster_path: "/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg",
      video: false,
      vote_average: 7.2,
      vote_count: 387,
      overview:
        "A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.",
      release_date: "2022-02-10",
      title: "Uncharted",
      id: 335787,
      adult: false,
      backdrop_path: "/cTTggc927lEPCMsWUsdugSj6wAY.jpg",
      popularity: 1313.476,
      media_type: "movie",
    },
    {
      genre_ids: [28, 80, 14],
      original_language: "en",
      original_title: "Fistful of Vengeance",
      poster_path: "/3cccEF9QZgV9bLWyupJO41HSrOV.jpg",
      video: false,
      vote_average: 5.5,
      vote_count: 61,
      overview:
        "A revenge mission becomes a fight to save the world from an ancient threat when superpowered assassin Kai tracks a killer to Bangkok.",
      release_date: "2022-02-17",
      title: "Fistful of Vengeance",
      id: 890656,
      adult: false,
      backdrop_path: "/9nKZvyAnGOHEQFpuaPoqVma8E3.jpg",
      popularity: 422.556,
      media_type: "movie",
    },
    {
      original_language: "en",
      original_title: "House of Gucci",
      poster_path: "/vHla3Ej2m53rNmvmYkzvennLrKn.jpg",
      video: false,
      vote_average: 6.7,
      overview:
        "When Patrizia Reggiani, an outsider from humble beginnings, marries into the Gucci family, her unbridled ambition begins to unravel the family legacy and triggers a reckless spiral of betrayal, decadence, revenge, and ultimately…murder.",
      release_date: "2021-11-24",
      vote_count: 1144,
      title: "House of Gucci",
      adult: false,
      backdrop_path: "/jdLsmpqmP1wTdFUPtmxMnYgoifT.jpg",
      id: 644495,
      genre_ids: [18, 80, 53],
      popularity: 468.33,
      media_type: "movie",
    },
    {
      id: 568124,
      overview:
        "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
      release_date: "2021-11-24",
      adult: false,
      backdrop_path: "/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg",
      genre_ids: [16, 35, 10751, 14],
      vote_count: 4623,
      original_language: "en",
      original_title: "Encanto",
      poster_path: "/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
      title: "Encanto",
      video: false,
      vote_average: 7.8,
      popularity: 3074.945,
      media_type: "movie",
    },
    {
      genre_ids: [28, 12, 14, 878],
      original_language: "en",
      original_title: "Eternals",
      poster_path: "/bcCBq9N1EMo3daNIjWJ8kYvrQm6.jpg",
      title: "Eternals",
      vote_average: 7.2,
      vote_count: 4490,
      overview:
        "The Eternals are a team of ancient aliens who have been living on Earth in secret for thousands of years. When an unexpected tragedy forces them out of the shadows, they are forced to reunite against mankind’s most ancient enemy, the Deviants.",
      release_date: "2021-11-03",
      video: false,
      id: 524434,
      adult: false,
      backdrop_path: "/c6H7Z4u73ir3cIoCteuhJh7UCAR.jpg",
      popularity: 1934.727,
      media_type: "movie",
    },
    {
      id: 110492,
      name: "Peacemaker",
      first_air_date: "2022-01-13",
      backdrop_path: "/ctxm191q5o3axFzQsvNPlbKoSYv.jpg",
      vote_count: 1180,
      genre_ids: [10759, 10765, 18],
      vote_average: 8.6,
      original_language: "en",
      poster_path: "/hE3LRZAY84fG19a18pzpkZERjTE.jpg",
      original_name: "Peacemaker",
      origin_country: ["US"],
      overview:
        "The continuing story of Peacemaker – a compellingly vainglorious man who believes in peace at any cost, no matter how many people he has to kill to get it – in the aftermath of the events of “The Suicide Squad.”",
      popularity: 2060.522,
      media_type: "tv",
    },
    {
      overview:
        "It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself. Though devastated by this grim reality, Tanjiro resolves to become a “demon slayer” so that he can turn his sister back into a human, and kill the demon that massacred his family.",
      id: 85937,
      name: "Demon Slayer: Kimetsu no Yaiba",
      vote_count: 3597,
      genre_ids: [16, 10765, 10759],
      backdrop_path: "/iBAtBLqCMON3NPIjyQ1wdMbpTAk.jpg",
      original_language: "ja",
      original_name: "鬼滅の刃",
      origin_country: ["JP"],
      first_air_date: "2019-04-06",
      poster_path: "/wrCVHdkBlBWdJUZPvnJWcBRuhSY.jpg",
      vote_average: 8.8,
      popularity: 284.388,
      media_type: "tv",
    },
    {
      original_language: "en",
      original_title: "Marry Me",
      poster_path: "/ko1JVbGj4bT8IhCWqjBQ6ZtF2t.jpg",
      vote_count: 171,
      video: false,
      id: 615904,
      release_date: "2022-02-09",
      vote_average: 6.9,
      title: "Marry Me",
      adult: false,
      backdrop_path: "/koaxq5QbARIlfxCOR89atPHv367.jpg",
      overview:
        "Music superstars Kat Valdez and Bastian are getting married before a global audience of fans. But when Kat learns, seconds before her vows, that Bastian has been unfaithful, she decides to marry Charlie, a stranger in the crowd, instead.",
      genre_ids: [35, 10749, 10402],
      popularity: 1483.174,
      media_type: "movie",
    },
    {
      backdrop_path: "/sjx6zjQI2dLGtEL0HGWsnq6UyLU.jpg",
      genre_ids: [10759, 10765],
      original_language: "en",
      id: 115036,
      poster_path: "/gNbdjDi1HamTCrfvM9JeA94bNi2.jpg",
      original_name: "The Book of Boba Fett",
      origin_country: ["US"],
      overview:
        "Legendary bounty hunter Boba Fett and mercenary Fennec Shand must navigate the galaxy’s underworld when they return to the sands of Tatooine to stake their claim on the territory once ruled by Jabba the Hutt and his crime syndicate.",
      first_air_date: "2021-12-29",
      vote_count: 1115,
      vote_average: 8.3,
      name: "The Book of Boba Fett",
      popularity: 1180.168,
      media_type: "tv",
    },
    {
      adult: false,
      backdrop_path: "/hB4ibOHXm1Xl0IbuYVioktDGUWJ.jpg",
      genre_ids: [18, 35],
      original_language: "en",
      original_title: "Licorice Pizza",
      poster_path: "/jD98aUKHQZNAmrk0wQQ9wmNQPnP.jpg",
      vote_count: 342,
      video: false,
      vote_average: 7.1,
      title: "Licorice Pizza",
      overview:
        "The story of Alana Kane and Gary Valentine growing up, running around and going through the treacherous navigation of first love in the San Fernando Valley, 1973.",
      id: 718032,
      release_date: "2021-11-26",
      popularity: 194.834,
      media_type: "movie",
    },
    {
      id: 800510,
      overview:
        "A tech worker with agoraphobia discovers recorded evidence of a violent crime but is met with resistance when she tries to report it. Seeking justice, she must do the thing she fears the most: she must leave her apartment.",
      release_date: "2022-02-10",
      adult: false,
      backdrop_path: "/mruT954ve6P1zquaRs6XG0hA5k9.jpg",
      vote_count: 131,
      genre_ids: [53],
      vote_average: 6.3,
      original_language: "en",
      original_title: "Kimi",
      poster_path: "/okNgwtxIWzGsNlR3GsOS0i0Qgbn.jpg",
      title: "Kimi",
      video: false,
      popularity: 2922.399,
      media_type: "movie",
    },
    {
      overview:
        "When a single mom and her two kids arrive in a small town, they begin to discover their connection to the original Ghostbusters and the secret legacy their grandfather left behind.",
      release_date: "2021-11-11",
      id: 425909,
      adult: false,
      backdrop_path: "/EnDlndEvw6Ptpp8HIwmRcSSNKQ.jpg",
      genre_ids: [14, 35, 12],
      title: "Ghostbusters: Afterlife",
      original_language: "en",
      original_title: "Ghostbusters: Afterlife",
      poster_path: "/sg4xJaufDiQl7caFEskBtQXfD4x.jpg",
      vote_count: 2088,
      video: false,
      vote_average: 7.7,
      popularity: 1313.097,
      media_type: "movie",
    },
    {
      title: "The Batman",
      overview:
        "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
      release_date: "2022-03-01",
      id: 414906,
      adult: false,
      backdrop_path: "/rvtdN5XkWAfGX6xDuPL6yYS2seK.jpg",
      genre_ids: [28, 80, 18],
      original_language: "en",
      original_title: "The Batman",
      poster_path: "/3VFI3zbuNhXzx7dIbYdmvBLekyB.jpg",
      vote_count: 0,
      video: false,
      vote_average: 0.0,
      popularity: 411.063,
      media_type: "movie",
    },
    {
      overview:
        "An ambitious carnival man with a talent for manipulating people with a few well-chosen words hooks up with a female psychiatrist who is even more dangerous than he is.",
      release_date: "2021-12-02",
      adult: false,
      backdrop_path: "/mqDnDhG5N6fn1H4MKQqr8E5wfeK.jpg",
      vote_count: 815,
      genre_ids: [80, 18, 53],
      id: 597208,
      original_language: "en",
      original_title: "Nightmare Alley",
      poster_path: "/680klE0dIreQQOyWKFgNnCAJtws.jpg",
      title: "Nightmare Alley",
      video: false,
      vote_average: 7.2,
      popularity: 2931.715,
      media_type: "movie",
    },
    {
      backdrop_path: "/yvKrycViRMQcIgdnjsM5JGNWU4Q.jpg",
      first_air_date: "2013-04-07",
      genre_ids: [10765, 16, 10759],
      id: 1429,
      name: "Attack on Titan",
      origin_country: ["JP"],
      original_language: "ja",
      original_name: "進撃の巨人",
      overview:
        "Several hundred years ago, humans were nearly exterminated by Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest Titans. Flash forward to the present and the city has not seen a Titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a Colossal Titan that appears out of thin air. As the smaller Titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single Titan and take revenge for all of mankind.",
      poster_path: "/aiy35Evcofzl7hASZZvsFgltHTX.jpg",
      vote_average: 8.6,
      vote_count: 4018,
      popularity: 281.924,
      media_type: "tv",
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};
